default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hero_scheduler_development

test:
  <<: *default
  database: hero_scheduler_test
#
production:
  <<: *default
  database: hero_scheduler_production
  username: hero_scheduler
  password: <%= ENV['HERO_SCHEDULER_DATABASE_PASSWORD'] %>
